name: Create Feature Branches

on:
  create:
    branches:
      - "feature/*" # Trigger on any branch starting with 'feature/'

permissions: write-all

jobs:
  create-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get branch name
        run: echo "${{ github.ref }}"
        id: branch_name

      - name: Create branches and push on GitHub
        run: |
          branch_name=$(echo "${{ github.ref }}" | cut -d '/' -f 4)
          dev_branch="${branch_name}-dev"
          main_branch="${branch_name}-main"
          current_branch=$(git branch --show-current)  # Get the current branch name

          # creating remote branches
          git pull
          git push origin $current_branch:$dev_branch
          git push origin $current_branch:$main_branch

          # Set upstream for dev and master separately
          git fetch
          git branch --set-upstream-to=origin/$dev_branch $current_branch
          git branch --set-upstream-to=origin/$main_branch $current_branch
